### ISSUE TITLE
Unclear installation instructions and NaN:NaN:NaN displayed

### ISSUE THREAD

**Issue by eugenefvdm** [cloudstudio/nova-time-tracker-field#1]
It's unclear from the installation instructions if a field must be created in your model's database, but but I tried creating 'seconds' as a 'integer' field.

The first time you save the model, it works. Then on subsequent Updates it displays:
NaN:NaN:NaN

Please assist.

**Comment by cloudstudio** [comment]
Hello @eugenevdm  if you use "seconds" its easy, just remove format option 👍 

```
TimeTracker::make('seconds')

```
